[project]
name = "agentic-network-mapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "openai-agents[litellm]==0.0.15",
    "python-nmap>=0.7.1",
]
